project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: ""
  description: "Home website of Sea Through Science Ltd." 
  page-footer:
    left: "&copy; Copyright 2024, Adam N. H. Smith<br>"
    right: "This site is under construction with ❤️ and [Quarto](https://quarto.org/)."
  favicon: /favicon/favicon-96x96.png
  navbar:
    pinned: true
    logo: /logo/nobg_whwr_horiz.png

    # your sub-pages
    left:
      - text: "About"
        href: index.qmd
      - text: "Services"
        href: services/index.qmd
      - text: "Who are we?"
        href: who/index.qmd
      - text: "BRUV"
        href: bruv/index.qmd
      - text: "BRUVmaps"
        menu:
          - text: "Otago 2025"
            href: bruvmaps/mapview_ota.qmd
          - text: "Hauraki Gulf 2024"
            href: bruvmaps/mapview_hau.qmd
          - text: "Fiordland 2024-25"
            href: bruvmaps/mapview_fld.qmd
          - text: "Southwest Pacific 2017"
            href: bruvmaps/mapview_swp.qmd
      - text: "Slides"
        href: slides/slides.qmd
      - text: "Contact"
        href: contact/index.qmd
    right:
      - icon: youtube
        href: https://www.youtube.com/@anhsmith
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?hl=en&user=5OvrU9IAAAAJ
      - icon: github
        href: https://github.com/anhsmith
      - icon: linkedin
        href: https://www.linkedin.com/in/adam-smith-1a723532/
      - icon: envelope
        href: "mailto:adam@seathrough.science"

# Don't touch unless you know what you are doing :) ------------

format:
  html:
    fontsize: 1.1em
    theme: 
      dark: [darkly, theme_darkly.scss, styles.scss]
      light: [flatly, theme_flatly.scss, styles.scss]
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    sidebar: true

execute:
  freeze: auto