project:
  type: website
  output-dir: docs

website:
  title: ""
  description: "Home website of Sea Through Science Ltd." 
  page-footer:
    left: "&copy; Copyright 2023, Adam N. H. Smith<br>"
    right: "This site is under construction with ❤️ and [Quarto](https://quarto.org/)."
  navbar:
    pinned: true
    logo: /img/sarah_mark.jpg

 # your sub-pages
    left:
      - text: "About"
        href: index.qmd
      - text: "Services"
        href: services/index.qmd
      - text: "Who are we?"
        href: who/index.qmd
      - text: "BRUV"
        href: bruv/index.qmd
      - text: "BRUVmaps"
        href: bruvmaps/index.qmd
      - text: "Slides"
        href: slides/slides.qmd
    right:
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?hl=en&user=5OvrU9IAAAAJ
      - icon: github
        href: https://github.com/anhsmith
      - icon: linkedin
        href: https://www.linkedin.com/in/adam-smith-1a723532/
      - icon: envelope
        href: "mailto:anhsmith@gmail.com"  


# Don't touch unless you know what you are doing :) ------------

format:
  html:
    fontsize: 1.1em
    theme: 
      light: [flatly, theme_flatly.scss]
      dark: [darkly, theme_darkly.scss]
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true

